AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Exclude:
    - src/tests/**/*

Metrics/MethodLength:
  Max: 20
  Exclude:
    - src/tests/**/*

Metrics/BlockLength:
  Exclude:
    - src/tests/**/*

Metrics/ClassLength:
  Max: 120
  Exclude:
    - src/tests/**/*
    - src/steps/generate_report.rb

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Exclude:
    - src/**/*

Rails/TimeZone:
  Exclude:
    - src/tests/**/*
